name: Dispatch sitemap to google

on:
  push:
    branches: 
      - master

jobs:
  upload_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '30s'
      - name: curl
        uses: wei/curl@v1.1.1
        with:
          args: http://www.google.com/ping?sitemap=https://sujingjhong.com/sitemap.xml
      - name: curl
        uses: wei/curl@v1.1.1
        with:
          args: http://www.bing.com/ping?sitemap=https://sujingjhong.com/sitemap.xml
